development:
  adapter: postgresql
  encoding: unicode
  database: d7mtvov43b465c
  pool: 5
  username: ajhnxexcpcioeo
  password:	NmdFmk-JDmy7Dmnu0jLM7xUb3Y
  host: ec2-54-227-251-13.compute-1.amazonaws.com
test:
  adapter: postgresql
  encoding: unicode
  database: epitool_test
  pool: 5
  username: jdhand90
  password:	rvhvxgpi90
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: epitool_production
  pool: 5
  username: jdhand90
  password:	rvhvxgpi90
  host: localhost
