development:
  adapter: postgresql
  encoding: unicode
  database: epitool_development
  pool: 5
  username: jdhand90
  password:	rvhvxgpi90
test:
  adapter: postgresql
  encoding: unicode
  database: epitool_test
  pool: 5
  username: jdhand90
  password:	rvhvxgpi90
production:
  adapter: postgresql
  encoding: unicode
  database: epitool_production
  pool: 5
  username: jdhand90
  password:	rvhvxgpi90
